// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAR1I7-m2uhYlLVAvjfCf_g7EOK9OloEE',
    appId: '1:632496812248:web:58aef53aa91d2eca9127ad',
    messagingSenderId: '632496812248',
    projectId: 'apple-c4200',
    authDomain: 'apple-c4200.firebaseapp.com',
    storageBucket: 'apple-c4200.firebasestorage.app',
    measurementId: 'G-4GW67R66WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR2PgU7Z7mcAdOy5lsHOB5IxWbU8b3DTg',
    appId: '1:632496812248:android:f52b7cdb18ce91d39127ad',
    messagingSenderId: '632496812248',
    projectId: 'apple-c4200',
    storageBucket: 'apple-c4200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGQ1tv5iM68zv1z-zzMCmMxCFNQEDaJgU',
    appId: '1:632496812248:ios:b549fab3ad1b7cc29127ad',
    messagingSenderId: '632496812248',
    projectId: 'apple-c4200',
    storageBucket: 'apple-c4200.firebasestorage.app',
    iosBundleId: 'com.apple.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGQ1tv5iM68zv1z-zzMCmMxCFNQEDaJgU',
    appId: '1:632496812248:ios:b549fab3ad1b7cc29127ad',
    messagingSenderId: '632496812248',
    projectId: 'apple-c4200',
    storageBucket: 'apple-c4200.firebasestorage.app',
    iosBundleId: 'com.apple.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAR1I7-m2uhYlLVAvjfCf_g7EOK9OloEE',
    appId: '1:632496812248:web:86ffc81d2d09d23e9127ad',
    messagingSenderId: '632496812248',
    projectId: 'apple-c4200',
    authDomain: 'apple-c4200.firebaseapp.com',
    storageBucket: 'apple-c4200.firebasestorage.app',
    measurementId: 'G-XZ0B65M99W',
  );
}
